//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaroGNCService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInformation
    {
        public long id { get; set; }
        public Nullable<long> idCustomer { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string commercialAssignment { get; set; }
        public string region { get; set; }
        public string subArea { get; set; }
        public Nullable<int> currentLines { get; set; }
        public Nullable<int> valueArpu { get; set; }
        public Nullable<int> averageArpuLine { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
    }
}
